default_config:

logger:
  default: info
  logs:
    custom_components.ecodevices_rt2: debug
# If you need to debug uncommment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:

ecodevices_rt2:
  - name: EcoRT2
    host: "192.168.0.20"
    api_key: #!secret rt2_api_key
    scan_interval: 15
    devices:
      - name: Elec Puissance Appelee
        type: "api"
        component: "sensor"
        api_get: "Get"
        api_get_value: "P"
        api_get_entry: "INSTANT_POSTE1"
        device_class: "power"
        unit_of_measurement: "kW"
      - name: Counter 1
        type: "counter"
        id: 1
        unit_of_measurement: "$"
      - name: Temp Chambre
        icon: mdi:water-boiler
        type: "enocean"
        unit_of_measurement: "°C"
        id: 1
      - name: Index Total Poste 1
        type: "post"
        id: 1
      - name: Index Sous Poste 1-2
        type: "post"
        id: 1
        subpost: 1
      - name: Index TI1
        type: "supplierindex"
        id: 1
      - name: Toroid 1
        type: "toroid"
        id: 1
        unit_of_measurement: "$"
      - name: XHTL 1
        type: "xthl"
        id: 1
        unit_of_measurement: "°F"
      - name: API EnOcean1
        type: "api"
        component: "switch"
        api_get: "Get"
        api_get_value: "XENO"
        api_get_entry: "ENO ACTIONNEUR1"
        api_on_get: "SetEnoPC"
        api_on_get_value: "1"
        api_off_get: "ClearEnoPC"
        api_off_get_value: "1"
      - name: EnOcean2
        type: "enocean"
        component: "switch"
        id: 2
      - name: Relay1
        type: "relay"
        id: 1
      - name: VirtualOutput 1
        type: "virtualoutput"
        id: 1
      - name: X4FP Switch 1-2
        type: "x4fp"
        component: "switch"
        module: 1
        zone: 2
      - name: Heater 1-1
        type: "x4fp"
        component: "climate"
        module: 1
        zone: 1
      - name: DigitalInput 1
        type: "digitalinput"
        id: 1
      - name: API EnOcean2 Light
        type: "api"
        component: "light"
        api_get: "Get"
        api_get_value: "XENO"
        api_get_entry: "ENO ACTIONNEUR2"
        api_on_get: "SetEnoPC"
        api_on_get_value: "2"
        api_off_get: "ClearEnoPC"
        api_off_get_value: "2"
      - name: RelayLight
        type: "relay"
        component: "light"
        id: 2
      - name: EnOcean3 Light
        type: "enocean"
        component: "light"
        id: 3
      - name: VirtualOutput3 Light
        type: "virtualoutput"
        component: "light"
        id: 3
