default_config:

logger:
  default: info
  logs:
    custom_components.ecodevices_rt2: debug
# If you need to debug uncommment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:

ecodevices_rt2:
  - name: EcoRT2
    host: "192.168.0.20"
    port: 80 # Optional, default: 80
    api_key: #!secret rt2_api_key
    update_after_switch: 0.1
    scan_interval: 5
    devices:
      #### API Example
      - name: Elec Index HC (from API)
        type: "api"
        component: "sensor"
        api_get: "Index"
        api_get_value: "All"
        api_get_entry: "Index_TI1"
        device_class: "energy"
        unit_of_measurement: "Wh"
        state_class: "total_increasing"
      - name: EnOcean Switch 1 (from API)
        type: "api"
        component: "switch"
        api_get: "Get"
        api_get_value: "XENO"
        api_get_entry: "ENO ACTIONNEUR1"
        api_on_get: "SetEnoPC"
        api_on_get_value: "1"
        api_off_get: "ClearEnoPC"
        api_off_get_value: "1"

      #### Counter Example
      - name: Counter 1
        type: "counter"
        id: 1

      #### DigitalInput Example
      - name: DigitalInput 1
        type: "digitalinput"
        id: 1

      #### EnOcean Switch or Sensor Example
      - name: Bedroom temperature
        type: "enocean" # Using default component `sensor`
        id: 1
        unit_of_measurement: "°C"
        icon: mdi:thermometer
        device_class: "temperature"
      - name: EnOcean Switch 1
        type: "enocean"
        component: "switch"
        id: 1
      - name: EnOcean Switch 2 as Light
        type: "enocean"
        component: "light"
        id: 2

      #### Post and Sub-Post Example
      - name: Post 1
        type: "post"
        id: 1
      - name: Subpost 2 of Post 1
        type: "post"
        id: 1
        subpost: 2
        allow_zero: False

      #### Relay Example
      - name: Relay 1
        type: "relay" # Using default component `sensor`
        id: 1
      - name: Relay 2 as Light
        type: "relay"
        component: "light"
        id: 2

      #### SupplierIndex Example
      - name: Supplier Index 1 (EDF Info)
        type: "supplierindex"
        id: 1

      #### Toroid Example
      - name: Toroid 1 # 2 sensors
        type: "toroid"
        id: 1
      - name: Toroid 5 # 2 sensors
        type: "toroid"
        id: 5
        allow_zero: False

      #### VirtualOutput Example
      - name: Virtual Output 1
        type: "virtualoutput" # Using default component `sensor`
        id: 1
      - name: Virtual Output 2 as Light
        type: "virtualoutput"
        component: "light"
        id: 2

      #### X4FP (Heaters) Example
      - name: Heater Module 1 Zone 1
        type: "x4fp"
        component: "climate" # Can be omitted since default value
        module: 1
        zone: 1
      - name: Heater Module 1 Zone 2 as Switch
        type: "x4fp"
        component: "switch"
        module: 1
        zone: 2

      #### XTHL Example
      - name: XHTL 1
        type: "xthl"
        id: 1
